<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
<script>
    /**
     *  Promise 是ES6引入的异步编程的新解决档案 语法上Promise是一个构造函数
     *  用来封装异步操作并可以获取成功或者失败的结果
     *
     * 通过下面的操作可以把异步操作封装在 promise 中
     *
     */
        //    参数是函数类型 promise的三个状态 初始化 成功 失败
    const p = new Promise(function (resolve, reject) {
            setTimeout(function () {
                let data = '数据'
                // resolve(data)//当调用完 resolve之后 promise的状态就是成功

                let err = '失败'
                reject(err)//当调用了reject 就会传输失败数据 然后then的第二个函数执行
            }, 1000)
        })

    // 成功后就会调用 promise 对象的then方法
    // then()方法会接收两个函数类型的值的参数 两个都会有形参
    // 成功的形参叫做 value 失败的叫 reason
    p.then(function (value) {
        console.log(value); //返回了数据
    }, function (reason) {
        console.log(reason);
    })
    /*
        promise 封装 ajax操作
            接口地址: https://api.apiopen.top/getJoke
    */
    // 封装 到 promise
    const P = new Promise((resolve, reject) => {

        // .创建对象
        const xhr = new XMLHttpRequest();
        // 初始化
        xhr.open("GET", "https://api.apiopen.top/getJoke");
        //  发送
        xhr.send()
        // 绑定事件 处理响应结果
        xhr.onreadystatechange = function () {
            if (xhr.readyState === 4) {
                // 判断响应状态码 200-299
                if (xhr.status >= 200 && xhr.status < 300) {
                    // 表示成功
                    resolve(xhr.response);
                } else {
                    // 如果失败
                    reject(xhr.status);
                }
            }
        }
    })
    p.then(function (value) {
        console.log(value);
    }, function (reason) {
        console.error(reason);
    })


    // console.log("===========分界线");
    // promise then 方法返回结果的状态
    // 创建 promise 对象
    const p2 = new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve('用户数据')
        }, 1000)
    })
    const result = p2.then(value => {
        console.log(value)
        // return 1234 // value

        // 如果想 result 默认抛出错误可
        // 可以
        throw new Error("出错")
        // 或者// 如果想 result 默认抛出错误可  这个Promise状态的值 决定 then方法的值
        return new Promise((resolve, reject) => {
            reject(error)
        })
    }, reason => {
        console.warn(reason);
    })
    // promise then()范湖结果是promise 对象
    //  对象的状态由回调函数的执行结果来决定  默认返回成功的promise值 无论有无防护与照顾
    console.log(result);
    // p.then().then() 可以链式调用防止回调地狱

    // promise catch方法 catch就是then()不要第一个参数
    p.catch(function (reason) {

    })
</script>
</body>

</html>